trigger:
  branches:
    include:
      - main

pool:
  vmImage: ubuntu-latest

stages:
  - stage: CD_Sandbox
    jobs:
      - job: apply
        displayName: Apply
        variables:
          TF_STATE_BUCKET: "phoodie"
          TF_STATE_KEY: "TerraformStateFiles/ssh-key-rotation"
        steps:
          - checkout: self
            displayName: Checkout
            persistCredentials: "true"

          - script: |
              git config --global url."https://$(System.AccessToken)@dev.azure.com/phoodie".insteadOf "https://dev.azure.com/phoodie"
            displayName: "Set system access for module"

          - task: AWSShellScript@1
            displayName: Set AWS Credentials
            inputs:
              regionName: "ap-southeast-2"
              awsCredentials: "phoodie_sandbox"
              scriptType: "inline"
              inlineScript: |
                echo "##vso[task.setvariable variable=AWS_SECRET_ACCESS_KEY;]$AWS_SECRET_ACCESS_KEY"
                echo "##vso[task.setvariable variable=AWS_ACCESS_KEY_ID;]$AWS_ACCESS_KEY_ID"
          - script: |
              make init apply
            displayName: Terraform Apply
