services:
  terraform:
    image: hashicorp/terraform:1.9.2
    environment:
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY:-}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID:-}
      - AWS_SESSION_TOKEN=${AWS_SESSION_TOKEN:-}
      - TF_STATE_BUCKET=${TF_STATE_BUCKET:-}
      - TF_STATE_KEY=${TF_STATE_KEY:-}
    volumes:
      - "./:/project"
      - /var/run/docker.sock:/var/run/docker.sock
    working_dir: /project/terraform

  terraform-docs:
    image: quay.io/terraform-docs/terraform-docs:0.18.0
    volumes:
      - "./module:/project:ro"
    working_dir: /project

  tflint:
    build:
      dockerfile: ./containers/tflint.Dockerfile
    volumes:
      - "./:/project:ro"
    working_dir: /project
    entrypoint: tflint

  node-utils:
    build:
      dockerfile: ./containers/node-utils.Dockerfile
    volumes:
      - ".:/project"
    working_dir: /project
